from .cetl_user import CetlUser
from .course_submission_comment import CourseSubmissionVersionComment
from .course_submission_version import CourseSubmissionVersion
from .course_submission import CourseSubmission
from .course import Course
from .department import Department
from .faculty import Faculty
from .lecturer import Lecturer
from .programme_courses import programme_courses_m2m
from .programme import Programme
from .queue_item import QueueItem
from .queue import Queue
from .resource import Resource
from .user import User
